{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a0fefd",
    "module": "configlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "configlib-1.0.0.jar",
          "url": "configlib-1.0.0.jar",
          "size": 21336,
          "sha512": "63b1155280cc9b97d9de890846ec16a06ed79f656fc263167915975b135f64adbf00efe1841afa77dff662eb92a153178893540101c338e285027dd534032af5",
          "sha256": "02ead3358ca8ae51b1cd77567cfe1fbdc741e091c71643ca14ea1342696e923c",
          "sha1": "3cf23e87f60d3b7597e3caa78aca630405b8394d",
          "md5": "155d6403e3c2595a0b358a86c873a972"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "configlib-1.0.0.jar",
          "url": "configlib-1.0.0.jar",
          "size": 21336,
          "sha512": "63b1155280cc9b97d9de890846ec16a06ed79f656fc263167915975b135f64adbf00efe1841afa77dff662eb92a153178893540101c338e285027dd534032af5",
          "sha256": "02ead3358ca8ae51b1cd77567cfe1fbdc741e091c71643ca14ea1342696e923c",
          "sha1": "3cf23e87f60d3b7597e3caa78aca630405b8394d",
          "md5": "155d6403e3c2595a0b358a86c873a972"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configlib-1.0.0-sources.jar",
          "url": "configlib-1.0.0-sources.jar",
          "size": 7779,
          "sha512": "a628502ae80e39ebd78e521d493185aed7a66de6cb00227f7e4cabc03c446e2e3562636f02bf82877606cc7182a745f4e8571c1cc88a2654514fac6ad74e3c22",
          "sha256": "3d6737a1121451cbeb909eed539e8902eb8b2419578ca096abc28b48830d20fd",
          "sha1": "ec3242006a09d58d3ce1b21e5ac0f5ba6920c0bb",
          "md5": "c1befc08db4c9bac73a5040f351d643b"
        }
      ]
    }
  ]
}
