{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a0fefd",
    "module": "configlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "configlib-1.0.0.jar",
          "url": "configlib-1.0.0.jar",
          "size": 21584,
          "sha512": "3453264059d7b83bbc866a5543992224d3b5ac2065dbe4b6dafeb4b38435d968935e52b4a0335ca4989acb42dc4431fd7d8e1a3b62ee7f136edcac45702aa5b7",
          "sha256": "0df0a20aea7e10cd9665c66d4cf5030cb306affdacde82a2e950c79120782b1f",
          "sha1": "238ef9da55bf489968ea7d77ce6d5b916499a9d1",
          "md5": "1e338510ea5afc7cdbf71da898dc2083"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "configlib-1.0.0.jar",
          "url": "configlib-1.0.0.jar",
          "size": 21584,
          "sha512": "3453264059d7b83bbc866a5543992224d3b5ac2065dbe4b6dafeb4b38435d968935e52b4a0335ca4989acb42dc4431fd7d8e1a3b62ee7f136edcac45702aa5b7",
          "sha256": "0df0a20aea7e10cd9665c66d4cf5030cb306affdacde82a2e950c79120782b1f",
          "sha1": "238ef9da55bf489968ea7d77ce6d5b916499a9d1",
          "md5": "1e338510ea5afc7cdbf71da898dc2083"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configlib-1.0.0-sources.jar",
          "url": "configlib-1.0.0-sources.jar",
          "size": 7007,
          "sha512": "3e72c329856e296f7400609682fc96779f5d3fe96a3bbb939c64c2c51fa442e149649cf154f89af414313ff8c9a99198b2296793ab39cdaf3403cbeeca5d35dd",
          "sha256": "bcea2795413897440800cce00c2faeb5b647873a7739dfeb8519de42ea72cb78",
          "sha1": "de2f21659ebd16c893451757ba0cc33a619c0241",
          "md5": "9cb447540d1863f9a50cfcf89ba2f119"
        }
      ]
    }
  ]
}
