{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a0fefd",
    "module": "configlib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "configlib-1.0.1.jar",
          "url": "configlib-1.0.1.jar",
          "size": 33233,
          "sha512": "9aba5efb33d37778367030d03096dab7f4c65f6096ecdff029d538ab66011ba1110c9700688462218328373019f127e523b193ed965c97120586a22bbb933c85",
          "sha256": "8771e7f737194d6c7f1ceeb2415a3861caa746dc00c8b605f3e09ee56ccdd4ae",
          "sha1": "e4006a9482b07d2b0cdbf929da40ef3cce37f273",
          "md5": "17c4974a4e34f27beee2abe3b19f529a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "configlib-1.0.1.jar",
          "url": "configlib-1.0.1.jar",
          "size": 33233,
          "sha512": "9aba5efb33d37778367030d03096dab7f4c65f6096ecdff029d538ab66011ba1110c9700688462218328373019f127e523b193ed965c97120586a22bbb933c85",
          "sha256": "8771e7f737194d6c7f1ceeb2415a3861caa746dc00c8b605f3e09ee56ccdd4ae",
          "sha1": "e4006a9482b07d2b0cdbf929da40ef3cce37f273",
          "md5": "17c4974a4e34f27beee2abe3b19f529a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configlib-1.0.1-sources.jar",
          "url": "configlib-1.0.1-sources.jar",
          "size": 15162,
          "sha512": "68bc607f2d4d2a297b4e75c1ae46e4be348a1f8039154b15a3aeb6089f24b460a7440013718af88ee5e50f4361fe6e1e339397532e4b83148de26f670943336f",
          "sha256": "9bc1ab3f5db01f7da7cbad8c119ba3e5a466198351e7bf0daf8c03f3e66efd4a",
          "sha1": "ec616f73d71a464041a72e8cfa607d1bbe81c5ba",
          "md5": "326b2d0b0015cbccc5bbb9fdf0b216a1"
        }
      ]
    }
  ]
}
