{
  "formatVersion": "1.1",
  "component": {
    "group": "com.a0fefd",
    "module": "configlib",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "configlib-1.0.1.jar",
          "url": "configlib-1.0.1.jar",
          "size": 32499,
          "sha512": "0d058392210d27c38d430efebb33db7a611eca60c7b5824db4f52b5192797481682e20c4d6065fcea00c3b496e3759f8b98d26738c5610b62bc5c3d09646a326",
          "sha256": "45031c525293c169cb14dfc980e7906a32bff62e1567afad7fe6d63e80bcdcbe",
          "sha1": "3fd0ea963e3c22d2f20a3829bf2abc819e7087f7",
          "md5": "2df9ae99f7fb9e6cad71efac48a9b7fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.19.3"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.155.2+26.1.2"
          }
        }
      ],
      "files": [
        {
          "name": "configlib-1.0.1.jar",
          "url": "configlib-1.0.1.jar",
          "size": 32499,
          "sha512": "0d058392210d27c38d430efebb33db7a611eca60c7b5824db4f52b5192797481682e20c4d6065fcea00c3b496e3759f8b98d26738c5610b62bc5c3d09646a326",
          "sha256": "45031c525293c169cb14dfc980e7906a32bff62e1567afad7fe6d63e80bcdcbe",
          "sha1": "3fd0ea963e3c22d2f20a3829bf2abc819e7087f7",
          "md5": "2df9ae99f7fb9e6cad71efac48a9b7fc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "configlib-1.0.1-sources.jar",
          "url": "configlib-1.0.1-sources.jar",
          "size": 14558,
          "sha512": "c6415d4780a0238e7bedd06ac61f6793cafbe121ece146ca6b451cb7258166f536dccb0c964f24aa1f953563d7bc47a2647a3ed673e36a628e0f2c51802ec95e",
          "sha256": "edf21aa5e1f9b5316fffc65f7075479dbab21e1a796b3f0602638c3fe9891a87",
          "sha1": "440bbb8158f620befeded7a881e9b445224aeb21",
          "md5": "583bf78d251f2ee1477a5b7068dc30fa"
        }
      ]
    }
  ]
}
